mutation addData($input: [random_insert_input!]!){
        insert_random(objects: $input){
                returing{
                        id
                        title
                        desc
                        value
                }
        }
}