query getEvent($id:uuid!) {
  events_by_pk(id:$id) {
    id
    thumbnail
    title
    time
    price
    location_id
    category_id
    
    event_medias{
      media{
        url
      }
    }
  
    user {
      first_name
      last_name
      photo_url
      __typename
    }
    
    description
    venue
    tags {
      tag_id
      tag {
        id
        name
        __typename
      }
      __typename
    }
    follows{
      user{
        id  
      }
    }
    followers_count: follows_aggregate{
      aggregate{
        count
      }
    }
    location {
      area{
        id
        name
      }

      city{
        name
        id
      }
      area_id
      city_id
       location
    }
    __typename
  }
}