query getEvents($filter:events_bool_exp, $sort: [events_order_by!], $offset:Int, $limit:Int){
  events(where:$filter, order_by:$sort, limit:$limit, offset:$offset){
    id
    thumbnail
    title
    time
    price
    location_id
    user{
      first_name
      last_name
    }
    description
    tags{
      tag_id
      tag{
        name
      }
    }
    location{
      id
      location
      
    }
    
  }
}