query getEvents($filter:events_bool_exp, $order: [events_order_by!], $offset:Int, $limit:Int){
  events(where:$filter, order_by:$order, limit:$limit, offset:$offset){
    id
    thumbnail
    event_medias{
      media{
        url
      }
    }
    title
    time
    price
    location_id
    bookmarks{
      user{
        id
      }
    }
    follows{
      user{
        id
      }
    }
    tickets{
      user{
        id
      }
    }
    followers_count: follows_aggregate{
      aggregate{
        count
      }
    }
    user{
      id
      first_name
      last_name
    }
    description
    tags{
      tag_id
      tag{
        name
      }
    }
    location{
      id
      location
      
    }
    
  }
}